#!/bin/bash
set -e;

# Check if name is specified
if [[ $1 == memcached:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
    if [[ ! -d "$PLUGIN_PATH/link" ]]; then
        echo "Link plugin not found... Did you install it from https://github.com/rlaneve/dokku-link?"
        exit 1
    fi

    LINK_NAME="memcached"
    CONTAINER_NAME="memcached/$APP"
    MEMCACHE_PORT=11211
fi

case "$1" in

  memcached:create)
    # Check if Memcached container is installed
    IMAGE=$(docker images | grep "jezdez/memcached" | awk '{print $3}')
    if [[ -z $IMAGE ]]; then
        echo "Memcached image not found... Did you run 'dokku plugins-install'?"
        exit 1
    fi

    # Stop existing container with the same persistent Memcached
    ID=$(docker ps | grep "$CONTAINER_NAME":latest |  awk '{print $1}')
    if [[ ! -z "$ID" ]]; then
        docker stop $ID > /dev/null
    fi
    
    # Fork Memcached image
    ID=$(docker run -d jezdez/memcached exit 0)
    docker wait $ID > /dev/null
    IMAGE=$(docker commit $ID)
    docker tag $IMAGE $CONTAINER_NAME
    # Launch container
    docker run -name=$CONTAINER_NAME -p $MEMCACHE_PORT -d $CONTAINER_NAME \
        /usr/bin/memcached -u memcache -p $MEMCACHE_PORT -m 64 -l 0.0.0.0

    # Link to a potential existing app
    dokku memcached:link $APP $APP
    echo
    echo "-----> Memcached container created: $CONTAINER_NAME"
    sleep 1
    dokku memcached:info $APP
    ;;

  memcached:delete)
    # Stop the container
    ID=$(docker ps -a | grep "$CONTAINER_NAME":latest |  awk '{print $1}')
    if [[ ! -z $ID ]]; then
        docker stop $ID > /dev/null
        docker rm $ID  > /dev/null
    fi

    # unlink this container as "redis"
    dokku link:delete "$APP" "$CONTAINER_NAME" "$LINK_NAME"
    dokku config:unset "$APP" MEMCACHE_SERVERS
    echo
    echo "-----> Memcached container deleted: $CONTAINER_NAME"
    ;;

  memcached:info)
    ID=$(docker ps -a | grep "$CONTAINER_NAME":latest | awk '{print $1}')
    IP=$(docker inspect $ID | grep IPAddress | cut -d '"' -f 4)
    DOCKER_GATEWAY=$(docker inspect $ID | grep Gateway | awk '{ print $2 }' | tr -d ',"')
    PORT=$(docker port $ID $MEMCACHE_PORT | cut -d":" -f2)
    echo
    echo "       Host: ${IP}"
    echo "       Gateway: ${DOCKER_GATEWAY}"
    echo "       Port: ${MEMCACHE_PORT} -> ${PORT}"
    echo
    ;;

  memcached:link)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $3 ]]; then
            echo "You must specify a container name"
            exit 1
        fi
        CONTAINER_NAME="memcached/$3"

        # link this container as "redis"
        dokku link:create "$APP" "$CONTAINER_NAME" "$LINK_NAME"

        # figure out IP to set env var
        ID=$(docker ps -a | grep "$CONTAINER_NAME":latest |  awk '{print $1}')
        IP=$(docker inspect $ID | grep IPAddress | cut -d '"' -f 4)
        DOCKER_GATEWAY=$(docker inspect $ID | grep Gateway | awk '{ print $2 }' | tr -d ',"')
        dokku config:set "$APP" MEMCACHE_SERVERS="${DOCKER_GATEWAY}:${MEMCACHE_PORT}"
        echo "-----> $APP linked to $CONTAINER_NAME container"
    fi
    ;;

  memcached:logs)
    ID=$(docker ps -a | grep "$CONTAINER_NAME":latest |  awk '{print $1}')
    docker logs $ID | tail -n 100
    ;;

  help)
    cat && cat<<EOF
    memcached:create <app>                          Create a Memcached container
    memcached:delete <app>                          Delete specified Memcached container
    memcached:info <app>                            Display container informations
    memcached:link <app> <container>                Link an app to a Memcached container
    memcached:logs <app>                            Display last logs from Memcached container
EOF
    ;;

esac
